version: 2
jobs:
  build:
    docker:
      - image: circleci/node:stretch

    steps:
      - checkout

      - run:
          name: Greeting from Infovinity Systems Pvt. Ltd.
          command: echo Hello, from Prakash Khandelwal.
          
      - run:
          name: Installing dependencies for Karma Project.
          command: npm install
          
      - run:
          name : App upload and Set app id in environment variable.
          command : |
            APP_UPLOAD_RESPONSE=$(curl -u "prakashkhandelwa5:tcs58Ga5ZnjKxVHq4NEp" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@apps/karma-latest.apk")
            echo "APP_UPLOAD_RESPONSE :  " + $APP_UPLOAD_RESPONSE
            APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
            if [ $APP_ID != null ]; then
              echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
              echo "export BROWSERSTACK_APP_ID=$APP_ID" >> $BASH_ENV;
              source $BASH_ENV;
              echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
            else
              UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
              echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
              exit 1;
            fi
            
      - run:
          name : Download BrowserStack Local binary and start it.
          command : |
            # Download the browserstack binary file
            wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
            # Unzip it
            unzip BrowserStackLocal-linux-x64.zip
            # Run the file with user's access key
            ./BrowserStackLocal --key tcs58Ga5ZnjKxVHq4NEp
          background: true
          
      - run:
          name: Running Browserstack Test. 
          command: npm run test           
            
      - run:
            name: Print the Current Time
            command: date