const applycardVM = {
  actualHeaderTitle: '',
  expectedHeaderTitle: 'ADD A CARD',
  addCardMessage: '',
  actualAmountText: '',
  expectedAmountText: 'AMOUNT',
  actualDurationText: '',
  expectedDurationText: 'DURATION',
  footerTextMsg: '',
  actualOneMonthDuration: '',
  expectedOneMonthDuration: '1 Month',
  actualSecondMonthDuration: '',
  expectedSecondMonthDuration: '2 Months',
  actualThirdMonthDuration: '',
  expectedThirdMonthDuration: '3 Months',
  actualAmountValue: '',
  expectedAmountValue: '£20',
  actualSuccesstext1: '',
  expectedSuccesstext1: 'Success!',
  actualSuccesstext2: '',
  expectedtext2: 'Your card is added to your wallet and is ready to be used at Tesco’s',
  actualBalancText: '',
  expectedBalancText: 'BALANCE',
  actualtwentyPound: '',
  expectedtwentyPound: '£20',
  actualIncomeDetailScreenHeaderTitle: '',
  expectedIncomeDetailScreenHeaderTitle: 'INCOME DETAILS ',
  actualHeaderTextOnIncomeDetailsScreen: '',
  actualCardStatusText: '',
  expectedCardStatusText: 'APPLICATION IS SUBMITTED',//APPLICATION IS PROCESSING, 'APPLICATION IS SUBMITTED'
  actualMonthlyIncomeErrorMsg: '',
  expectedMonthlyIncomeErrorMsg: 'Entered amount should be between 50 - 99999',
  actualMonthlyIncomeMsg: '',
  actualmonthlyIncome: '',
  actualMontlyRent: '',
  actualnumberOfDependants: '',
  actualMonthlyRentError: '',
  expectedMonthlyRentError: 'Entered amount should be between 50 - 99999',
  HeaderMessage: '',
}

const archivedcardVM = {
  actualHeaderTextOfPAYVIA: '',
  expectedHeaderTextOfPAYVIA: 'PAY VIA BARCODE',
  actualInstructionsText: '',
  expectedInstructionsText: 'INSTRUCTIONS',
}

const giftcardVM = {
  actualHeaderTitleofAddaGift: '',
  expectedHeaderTitleofAddaGift: 'ADD A GIFT',
  actualHeaderTitleofInviteSpender: '',
  expectedHeaderTitleofInviteSpender: 'INVITE SPENDER',
  actualfirstNameErrorforAlphabeticMSG: '',
  expectedfirstNameErrorforAlphabeticMSG: 'Require only alphabetic characters',
  actualfirstNameErrorforlessCharactersMSG: '',
  expectedfirstNameErrorforlessCharactersMSG: 'Should be 2 characters or more',
  actualmobileErrorMSG: '',
  expectedmobileErrorMSG: 'Not a valid phone number.'
}

const networktestVM = {
  actualErrorTitle: '',
  expectedErrorTitle: 'Error',
  actualErrorMessage: '',
  expectedErrorMessage: 'Network error: Network request failed',
}

const registrationVM = {
  actualMobileErrormsg: '',
  actualPasswordErrormsg: '',
  expectedMobileErrormsg: 'Not a valid phone number.',
  expectedSixCharacterErrormsg: 'Should be 6 characters or more',
  actualotpErrorMsg: '',
  expectedotpErrormsg: 'GraphQL error: Verification Code does not match.',
  actualFirstNameErrorMsg: '',
  expectedFirstNameErrorMsg: 'Should be 2 characters or more',
  expectedFirstNameReqErrorMsg: 'Require only alphabetic characters',
  expectedPostalCodeValue: 'SW100ab',
  expectedEmailErrorMsg: 'Invalid email address',
  actualEmailErrorMsg: '',
  actualFirstNameValue: '',
  actualLastNameValue: '',
  actualeEmailValue: '',
  actualpostalErrorMsg: '',
  expectedpostalErrorMsg: 'Should be 5 characters or more',
  actualPostalCodeMsg: '',
  expectedPostalCodeMsg: 'Select the search icon to find the address',
  actualHeaderTextOfNewsandUpdateScreen: '',
  expectedHeaderTextOfNewsandUpdateScreen: 'NEWS AND UPDATES',
  actualHeaderTextOfAddressDetailsScreen: '',
  expectedHeaderTextOfAddressDetailsScreen: 'ADDRESS DETAILS',
  actualpostalCodeValue: '',
  actualHeaderTextOfVerifyYourIdentityScreen: '',
  expectedHeaderTextOfVerifyYourIdentityScreen: 'VERIFY YOUR IDENTITY',
  actualStep3and4Text: '',
  expectedStep3and4Text: 'Step 3 of 4: Quick ID check',
  actualHeaderTextOnYourNotificationScreen: '',
  expectedHeaderTextOnYourNotificationScreen: 'YOUR NOTIFICATIONS',
  actualfirstname: '',
  actuallastname: '',
  actualemailID: '',
  actualmobileNo: '',
  selectedAddressText: '',
  expectedBuildingName: '',
  expectedCityName: '',
  expectedCountryName: '',
  actualBuildingName: '',
  actualCityName: '',
  actualCountryName: '',
  expectedEmptyFirstName: 'First name',
  actuallastNameErrorMsg: '',
  expectedEmptyLastName: 'Last name',
  expectedPrivacyPageHeader: 'PRIVACY POLICY',
  expectedtTermsPageHeader: 'TERMS OF SERVICE',
}

const kycVM = {
  actualMonthlyIncomeMsg: '',
  expectedMonthlyIncomeMsg: 'Monthly net salary in pounds',
  HeaderMessage: '',
  actualHeaderTextOfHousingDetails: '',
  expectedHeaderTextOfHousingDetails: 'HOUSING DETAILS',
  actualMonthlyRentPlaceHolder: '',
  expectedMonthlyRentPlaceHolder: 'Monthly Rent',
  actualMonthlyMortgagePlaceHolder: '',
  expectedMonthlyMortgagePlaceHolder: 'Monthly Mortgage',
  actualMonthlyRentMortgageMsg: '',
  expectedMonthlyRentMortgageMsg: 'Monthly spend on housing rent',
  actualHeaderTextOfEmployerDetails: '',
  expectedHeaderTextOfEmployerDetails: 'EMPLOYER DETAILS',
  actualHeaderMessage: '',
  expectedHeaderMessage: 'Where do you currently work?',
  actualHeaderTextOfSelectWorkAddress: '',
  expectedHeaderTextOfSelectWorkAddress: 'SELECT WORK ADDRESS',
  fullEmployerName: '',
  EmployerName: '',
  EmployeeName1: '',
  empName: '',
  fullAddress: '',
  buildingName: '',
  laneName: '',
  city: '',
  country: '',
  actualEmployerName: '',
  actualBuildingName: '',
  actualCityName: '',
  actualCountryName: '',
  actualIDCardText: '',
  expectedIDCardText: 'ID MADE SIMPLE',
  actualStepText: '',
  expectedStepText: 'Step 3 of 4: Quick ID check',
  IDCardText1: '',
  IDCardText2: '',
  actualHeaderTextOfVerifyYourIdentity: '',
  expectedHeaderTextOfVerifyYourIdentity: 'VERIFY YOUR IDENTITY',
  takeaPictureText: '',
  actualCongratulationText: '',
  expectedCongratulationText: 'CONGRATULATIONS',
  actualApprovedText: '',
  expectedApprovedText: 'Your credit limit is approved.',
  actualHeaderTextOfEnjoy: '',
  expectedHeaderTextOfEnjoy: 'ENJOY',
}

export { applycardVM, archivedcardVM, giftcardVM, networktestVM, registrationVM, kycVM }