const registerAccessibilityId = {
  register: 'registerBtn-testId',
  login: 'loginBtn-testId',
  phone: 'phoneContainer-testId',
  password: 'passwordContainer-testId',
  aggrementCheckbox: 'aggrementCheckbox-testId',
  otp: 'otpContainer-testId',
  nextButton: 'nextBtn-testId',
  firstname: 'firstNameContainer-testId',
  lastname: 'lastNameContainer-testId',
  birthdate: 'birthDateContainer-testId',
  okbutton: 'OK',//'android:id/button1',//*[@class='UIAStaticText']
  email: 'emailIdContainer-testId',
  backButton: 'leftIconBtn-testId',
  postalcode: 'postalCodeContainer-testId',
  search: 'searchIcon-testId',
  signmeup: 'signMeUpBtn-testId',
  allow: 'allowBtn-testId',
  takeaselfie: 'startPictureBtn-testId',
  capture: 'captureSelfie-testId',
  done: 'doneBtn-testId',
  apply: 'applyScreen-testId',
  dashboard: 'dashboardScreen-testId',
  card: 'cardsScreen-testId',
  profile: 'profileScreen-testId',
  more: 'moreScreen-testId',
  terms: 'termsLink-testId',
  headerTitle: 'headerTitle-test',
  privacyPolicy: 'privacyPolicyLink-testId',
  otpErrorMsg: 'GraphQL error: Verification Code does not match.',
  resendlink: 'resendCodeLink-testId',
  building: 'buildingLaneContainer-testId',
  city: 'buildingLaneContainer-testId',
  country: 'countryNameContainer-testId',
}

const registerXPath = {
  login: '//*[@text=\'loginLink-testId\']',
  countdowntext: '//*[@text=concat(\'Haven\', "\'", \'t received the code, click \', \'"\', \'Resend Sms\')]',
  tickMark: '//android.view.ViewGroup[@content-desc="otpContainer-testId"]/android.widget.TextView',
  addressDetailsText: '//*[@text=\'Step 2 of 4: The address details\']',
  selectAddress: '(//*/*/*[@accessibilityLabel=\'selectHomeAddress-testId\'])[1]',
  skip: '//*[@text=\'skip\']',
  step3and4Text: '//*[@text=\'Step 3 of 4: Quick ID check\']',
  sport: '//*[@text=\'Sports\']',
  actualfirstname: '//*[@text=\'firstNameContainer-testId\']',
  actuallastname: '//*[@text=\'lastNameContainer-testId\']',
  actualemailID: '//*[@text=\'emailIdContainer-testId\']',
  actualmobileNo: '//*[@text=\'phoneNumberContainer-testId\']',
  mobileNoError: '//*[@text=\'Not a valid phone number.\']',
  sixCharactersError: '//*[@text=\'Should be 6 characters or more\']',
  twoCharacterError: '//*[@text=\'Should be 2 characters or more\']',
  onlyAlphanumericError: '//*[@text=\'Require only alphabetic characters\']',
  invalidemailError: '//*[@text=\'Invalid email address\']',
  fiveCharactersError: '//*[@text=\'Should be 5 characters or more\']',
  postalCodeMsg: '//*[@text=\'Select the search icon to find the address\']',
  actualAddressList: '//*[@id=\'NO ADDRESSES FOUND\' and @class=\'UIAStaticText\']',
}

export { registerAccessibilityId, registerXPath }